version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: meme-generator-app
    tty: true
    ports:
      - "8020:7001"
      - "5173:5173"
    working_dir: /app
    volumes:
      - ../../:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
    command: sh /app/containers/developer/initServeDev.sh
    links:
      - database

  database:
    image: mysql:8.1
    container_name: MySQL
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meme_generator
    volumes:
      - data-bd:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpMyAdmin
    tty: false
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: database
    ports:
      - "8010:80"
    links:
      - database

volumes:
  data-bd:
